- hosts: all
  remote_user: root
  gather_facts: false
  become: false
  vars:
     instance_state: 'present'
     tower_version: '3.4.3-1'
     plan: 't1.small.x86'
     facility: 'ewr1'

  tasks:
    - name: include the packet-provision role
      include_role:
        name: packet-provision

    - name: include the tower-install role
      include_role:
        name: tower-install
      when: instance_state == 'present'

    - name: navigate to tower login via default brower
      command: open "https://{{ hostvars[groups['tower'][0]]['ip_address'] }}"
      ignore_errors: true
      changed_when: false
      run_once: true
      delegate_to: localhost
      when: instance_state == 'present'
